#!/usr/bin/env bash
# Sets up a custom 404 page in Nginx

# Update and install Nginx
sudo apt update -y
sudo apt install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \\n    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        root /var/www/html;\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply the new configuration
sudo systemctl restart nginx
